spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_hrm
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  config:
    import: optional:file:.env

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
app:
  cookie:
    secure: ${COOKIE_SECURE:false}